#!/usr/bin/env ruby

infile = File.open(ARGV[0], 'r')
regex = /\d{4}:(\d{2}):(\d{2}):(\d{2})\s/
matches = {}
infile.each_line { |line|
	if line =~ regex
		thisMatch = regex.match(line)
		thisMatch = $~.captures[0].to_s+":00"
		thisMatch = thisMatch.to_sym
		puts $~.captures[0].to_sym
		if matches.has_key?(thisMatch)
			matches[thisMatch] += 1
		else
			matches[thisMatch] = 1
		end
	end
}

# infile = File.open(ARGV[0], 'r')
# regex = /\s((4|5)[0-9][0-9])\s(\d{3}|-)/
# resource = /\"[A-Z]+\s(.*)HTTP/
# matches = {}
# infile.each_line { |line|
# 	if line =~ regex
# 		thisMatch = resource.match(line)
# 		thisMatch = $~.captures[0].to_sym
# 		if matches.has_key?(thisMatch)
# 			matches[thisMatch] += 1
# 		else
# 			matches[thisMatch] = 1
# 		end
# 	end
# }

# infile = File.open(ARGV[0], 'r')
# regex = /\A\d{1,3}\.\d{1,3}\.\d{1,3}/
# matches = {}
# infile.each_line { |line|
# 	if line =~ regex
# 		thisMatch = regex.match(line)
# 		thisMatch = thisMatch[0].to_sym
# 		if matches.has_key?(thisMatch)
# 			matches[thisMatch] += 1
# 		else
# 			matches[thisMatch] = 1
# 		end
# 	end
# }

# infile = File.open(ARGV[0], 'r')
# regex = /\"GET(.*)HTTP/
# matches = {}
# infile.each_line { |line|
# 	if line =~ regex

# 		thisMatch = $~.captures[0].to_sym

# 		if matches.has_key?(thisMatch)
# 			matches[thisMatch] += 1
# 		else
# 			matches[thisMatch] = 1
# 		end
# 	end
# }

# begin
#

#matches.keys[1..10].each { |key| puts "#{key} => #{matches[key]}" }

# matches = Hash[matches.sort_by { |k,v| [v, k.to_s.split('.').map{ |octet| octet.to_i}]}.reverse!]

matches = Hash[matches.sort_by {|k,v| k }]
matches.keys[0..10].each { |key| puts "#{key} => #{matches[key]}" }

# 	matches = Hash[matches.sort_by {|k,v| v}.reverse]
# rescue IOError => e
# 	STDERR.puts "Infile error! #{e}"
# 	infile.close
# 	exit 1
# rescue => e
# 	STDERR.puts "File error! #{e}"
# 	exit 1
# end